services:
  - type: web
    name: sne-radar
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app_simple.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
